In [130]:
import numpy as np
import pandas as pd

movies = pd.read_csv('movies_2.csv')
movies.head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."

# exercise 1 
the number of rows and columns present in the data set (i.e. the shape of the dataframe)

columns present in the data set, along with the data type (use info or dtypes method)

check how many NaN we have for MPAA Rating, Budget, Gross, Release Date, Genre, Runtime, Rating and Rating Count columns

understand which kind of information each column represents

In [131]:
movies = pd.read_csv('./movies_2.csv')
movies

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [132]:
movies.shape  #the number of rows and columns present in the data set
movies.info
movies.dtypes
movies.info
movies.isnull().sum()
movies.columns

print(movies.isnull().sum()) #finding the total null values in each row

print(movies.columns) 

null_rows = movies[movies.isnull().any(axis=1)] #printing all the null rows
null_rows

MovieID           0
Title             1
MPAA Rating       1
Budget            1
Gross             1
Release Date      1
Genre             1
Runtime           1
Rating          108
Rating Count    108
Summary         120
dtype: int64
Index(['MovieID', 'Title', 'MPAA Rating', 'Budget', 'Gross', 'Release Date',
       'Genre', 'Runtime', 'Rating', 'Rating Count', 'Summary'],
      dtype='object')

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
327,328,Mr. & Mrs. Smith,PG-13,110000000.0,4.782075e+08,2005-06-07,Comedy,120.0,6.7,150380.0,NaN
359,360,300,R,60000000.0,4.541619e+08,2007-03-09,Action,155.0,8.1,681249.0,NaN
380,381,Marley and Me,PG,60000000.0,2.478000e+08,2008-12-25,Drama,115.0,4.7,252223.0,NaN
391,392,WALL-E,G,180000000.0,5.333000e+08,2008-06-23,Animation,97.0,7.6,429384.0,NaN
396,397,Taken,PG-13,25000000.0,2.268000e+08,2009-01-30,Thriller,90.0,7.6,473121.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Exercise2 
Get rid of the Summary column (use the drop() method)

In [133]:
new_movies = movies.drop('Summary',axis='columns')
new_movies

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0
...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [134]:
movies.head(5) #see sample list

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."

# Exercise 3 
use the rename method to change all columns names to lowercase, and replace spaces with underscores if the name is made of more than one word

In [135]:
movies.columns = movies.columns.str.lower().str.replace(' ', '_') #fixing the name to lowercase
movies.columns

Index(['movieid', 'title', 'mpaa_rating', 'budget', 'gross', 'release_date',
       'genre', 'runtime', 'rating', 'rating_count', 'summary'],
      dtype='object')

# exercise 4 
Get rid of the last row

In [136]:
movies = movies.drop(movies.index[-1])
movies.shape

(615, 11)

 # exercise 5
 the one containing NaN for each column (use drop() method and row index)

In [ ]:
movies.dropna(axis=1,ax)